/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AutoCallRouteImport } from './routes/auto-call'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWebOrdersRouteImport } from './routes/_app/web-orders'
import { Route as AppUsersRouteImport } from './routes/_app/users'
import { Route as AppTelesalesRouteImport } from './routes/_app/telesales'
import { Route as AppTasksRouteImport } from './routes/_app/tasks'
import { Route as AppStaffReportsRouteImport } from './routes/_app/staff-reports'
import { Route as AppStaffLiveRouteImport } from './routes/_app/staff-live'
import { Route as AppSmsSettingsRouteImport } from './routes/_app/sms-settings'
import { Route as AppSmsRouteImport } from './routes/_app/sms'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProductsRouteImport } from './routes/_app/products'
import { Route as AppPreordersRouteImport } from './routes/_app/preorders'
import { Route as AppOrdersRouteImport } from './routes/_app/orders'
import { Route as AppOrderSourcesRouteImport } from './routes/_app/order-sources'
import { Route as AppOrderPageTemplatesRouteImport } from './routes/_app/order-page-templates'
import { Route as AppOmsEndpointsRouteImport } from './routes/_app/oms-endpoints'
import { Route as AppMarketingRouteImport } from './routes/_app/marketing'
import { Route as AppInvoiceStickerSettingsRouteImport } from './routes/_app/invoice-sticker-settings'
import { Route as AppInvoiceNumberingSettingsRouteImport } from './routes/_app/invoice-numbering-settings'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppIntegrationsRouteImport } from './routes/_app/integrations'
import { Route as AppIncompleteOrdersRouteImport } from './routes/_app/incomplete-orders'
import { Route as AppFacebookOrdersRouteImport } from './routes/_app/facebook-orders'
import { Route as AppExpensesRouteImport } from './routes/_app/expenses'
import { Route as AppDbSetupRouteImport } from './routes/_app/db-setup'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCouriersRouteImport } from './routes/_app/couriers'
import { Route as AppCourierSettingsRouteImport } from './routes/_app/courier-settings'
import { Route as AppComplaintsRouteImport } from './routes/_app/complaints'
import { Route as AppChatSettingsRouteImport } from './routes/_app/chat-settings'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppAdvancePaymentSourcesRouteImport } from './routes/_app/advance-payment-sources'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders.index'
import { Route as AppMarketingIndexRouteImport } from './routes/_app/marketing.index'
import { Route as AppFacebookOrdersIndexRouteImport } from './routes/_app/facebook-orders.index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers.index'
import { Route as ApiPublicOmsProductsRouteImport } from './routes/api/public/oms-products'
import { Route as ApiPublicOmsInboundRouteImport } from './routes/api/public/oms-inbound'
import { Route as AppTasksReportsRouteImport } from './routes/_app/tasks.reports'
import { Route as AppTasksTaskIdRouteImport } from './routes/_app/tasks.$taskId'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders.new'
import { Route as AppOrdersBulkPrintRouteImport } from './routes/_app/orders.bulk-print'
import { Route as AppOrdersBulkInvoiceRouteImport } from './routes/_app/orders.bulk-invoice'
import { Route as AppMarketingWhatsappRouteImport } from './routes/_app/marketing.whatsapp'
import { Route as AppMarketingTemplatesRouteImport } from './routes/_app/marketing.templates'
import { Route as AppMarketingSmsRouteImport } from './routes/_app/marketing.sms'
import { Route as AppMarketingSettingsRouteImport } from './routes/_app/marketing.settings'
import { Route as AppFacebookOrdersSettingsRouteImport } from './routes/_app/facebook-orders.settings'
import { Route as AppFacebookOrdersPagesRouteImport } from './routes/_app/facebook-orders.pages'
import { Route as AppFacebookOrdersOrdersRouteImport } from './routes/_app/facebook-orders.orders'
import { Route as AppFacebookOrdersLogsRouteImport } from './routes/_app/facebook-orders.logs'
import { Route as AppExpensesRecurringRouteImport } from './routes/_app/expenses.recurring'
import { Route as AppExpensesPnlRouteImport } from './routes/_app/expenses.pnl'
import { Route as AppExpensesHistoryRouteImport } from './routes/_app/expenses.history'
import { Route as AppExpensesAccountsRouteImport } from './routes/_app/expenses.accounts'
import { Route as AppCustomersBlockedRouteImport } from './routes/_app/customers.blocked'
import { Route as AppCouriersCourierIdRouteImport } from './routes/_app/couriers.$courierId'
import { Route as ApiPublicWebhooksWpIncompleteRouteImport } from './routes/api/public/webhooks/wp-incomplete'
import { Route as ApiPublicWebhooksWoocommerceRouteImport } from './routes/api/public/webhooks/woocommerce'
import { Route as ApiPublicHooksWpIncompleteSyncRouteImport } from './routes/api/public/hooks/wp-incomplete-sync'
import { Route as ApiPublicHooksWooOrdersSyncRouteImport } from './routes/api/public/hooks/woo-orders-sync'
import { Route as ApiPublicHooksMetaAdsSyncRouteImport } from './routes/api/public/hooks/meta-ads-sync'
import { Route as ApiPublicHooksCourierStatusSyncRouteImport } from './routes/api/public/hooks/courier-status-sync'
import { Route as ApiPublicFacebookPageOrdersWebhookRouteImport } from './routes/api/public/facebook-page-orders/webhook'
import { Route as AppOrdersOrderIdInvoiceRouteImport } from './routes/_app/orders.$orderId.invoice'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AutoCallRoute = AutoCallRouteImport.update({
  id: '/auto-call',
  path: '/auto-call',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWebOrdersRoute = AppWebOrdersRouteImport.update({
  id: '/web-orders',
  path: '/web-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppTelesalesRoute = AppTelesalesRouteImport.update({
  id: '/telesales',
  path: '/telesales',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffReportsRoute = AppStaffReportsRouteImport.update({
  id: '/staff-reports',
  path: '/staff-reports',
  getParentRoute: () => AppRoute,
} as any)
const AppStaffLiveRoute = AppStaffLiveRouteImport.update({
  id: '/staff-live',
  path: '/staff-live',
  getParentRoute: () => AppRoute,
} as any)
const AppSmsSettingsRoute = AppSmsSettingsRouteImport.update({
  id: '/sms-settings',
  path: '/sms-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSmsRoute = AppSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPreordersRoute = AppPreordersRouteImport.update({
  id: '/preorders',
  path: '/preorders',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderSourcesRoute = AppOrderSourcesRouteImport.update({
  id: '/order-sources',
  path: '/order-sources',
  getParentRoute: () => AppRoute,
} as any)
const AppOrderPageTemplatesRoute = AppOrderPageTemplatesRouteImport.update({
  id: '/order-page-templates',
  path: '/order-page-templates',
  getParentRoute: () => AppRoute,
} as any)
const AppOmsEndpointsRoute = AppOmsEndpointsRouteImport.update({
  id: '/oms-endpoints',
  path: '/oms-endpoints',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingRoute = AppMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoiceStickerSettingsRoute =
  AppInvoiceStickerSettingsRouteImport.update({
    id: '/invoice-sticker-settings',
    path: '/invoice-sticker-settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppInvoiceNumberingSettingsRoute =
  AppInvoiceNumberingSettingsRouteImport.update({
    id: '/invoice-numbering-settings',
    path: '/invoice-numbering-settings',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppIncompleteOrdersRoute = AppIncompleteOrdersRouteImport.update({
  id: '/incomplete-orders',
  path: '/incomplete-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppFacebookOrdersRoute = AppFacebookOrdersRouteImport.update({
  id: '/facebook-orders',
  path: '/facebook-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDbSetupRoute = AppDbSetupRouteImport.update({
  id: '/db-setup',
  path: '/db-setup',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCouriersRoute = AppCouriersRouteImport.update({
  id: '/couriers',
  path: '/couriers',
  getParentRoute: () => AppRoute,
} as any)
const AppCourierSettingsRoute = AppCourierSettingsRouteImport.update({
  id: '/courier-settings',
  path: '/courier-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppComplaintsRoute = AppComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => AppRoute,
} as any)
const AppChatSettingsRoute = AppChatSettingsRouteImport.update({
  id: '/chat-settings',
  path: '/chat-settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvancePaymentSourcesRoute =
  AppAdvancePaymentSourcesRouteImport.update({
    id: '/advance-payment-sources',
    path: '/advance-payment-sources',
    getParentRoute: () => AppRoute,
  } as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrdersRoute,
} as any).lazy(() =>
  import('./routes/_app/orders.index.lazy').then((d) => d.Route),
)
const AppMarketingIndexRoute = AppMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppFacebookOrdersIndexRoute = AppFacebookOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppFacebookOrdersRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicOmsProductsRoute = ApiPublicOmsProductsRouteImport.update({
  id: '/api/public/oms-products',
  path: '/api/public/oms-products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOmsInboundRoute = ApiPublicOmsInboundRouteImport.update({
  id: '/api/public/oms-inbound',
  path: '/api/public/oms-inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksReportsRoute = AppTasksReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppTasksTaskIdRoute = AppTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => AppTasksRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppOrdersBulkPrintRoute = AppOrdersBulkPrintRouteImport.update({
  id: '/bulk-print',
  path: '/bulk-print',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppOrdersBulkInvoiceRoute = AppOrdersBulkInvoiceRouteImport.update({
  id: '/bulk-invoice',
  path: '/bulk-invoice',
  getParentRoute: () => AppOrdersRoute,
} as any)
const AppMarketingWhatsappRoute = AppMarketingWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingTemplatesRoute = AppMarketingTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingSmsRoute = AppMarketingSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppMarketingSettingsRoute = AppMarketingSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppMarketingRoute,
} as any)
const AppFacebookOrdersSettingsRoute =
  AppFacebookOrdersSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppFacebookOrdersRoute,
  } as any)
const AppFacebookOrdersPagesRoute = AppFacebookOrdersPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AppFacebookOrdersRoute,
} as any)
const AppFacebookOrdersOrdersRoute = AppFacebookOrdersOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppFacebookOrdersRoute,
} as any)
const AppFacebookOrdersLogsRoute = AppFacebookOrdersLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppFacebookOrdersRoute,
} as any)
const AppExpensesRecurringRoute = AppExpensesRecurringRouteImport.update({
  id: '/recurring',
  path: '/recurring',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppExpensesPnlRoute = AppExpensesPnlRouteImport.update({
  id: '/pnl',
  path: '/pnl',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppExpensesHistoryRoute = AppExpensesHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppExpensesAccountsRoute = AppExpensesAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppExpensesRoute,
} as any)
const AppCustomersBlockedRoute = AppCustomersBlockedRouteImport.update({
  id: '/customers/blocked',
  path: '/customers/blocked',
  getParentRoute: () => AppRoute,
} as any)
const AppCouriersCourierIdRoute = AppCouriersCourierIdRouteImport.update({
  id: '/$courierId',
  path: '/$courierId',
  getParentRoute: () => AppCouriersRoute,
} as any)
const ApiPublicWebhooksWpIncompleteRoute =
  ApiPublicWebhooksWpIncompleteRouteImport.update({
    id: '/api/public/webhooks/wp-incomplete',
    path: '/api/public/webhooks/wp-incomplete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksWoocommerceRoute =
  ApiPublicWebhooksWoocommerceRouteImport.update({
    id: '/api/public/webhooks/woocommerce',
    path: '/api/public/webhooks/woocommerce',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWpIncompleteSyncRoute =
  ApiPublicHooksWpIncompleteSyncRouteImport.update({
    id: '/api/public/hooks/wp-incomplete-sync',
    path: '/api/public/hooks/wp-incomplete-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksWooOrdersSyncRoute =
  ApiPublicHooksWooOrdersSyncRouteImport.update({
    id: '/api/public/hooks/woo-orders-sync',
    path: '/api/public/hooks/woo-orders-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMetaAdsSyncRoute =
  ApiPublicHooksMetaAdsSyncRouteImport.update({
    id: '/api/public/hooks/meta-ads-sync',
    path: '/api/public/hooks/meta-ads-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCourierStatusSyncRoute =
  ApiPublicHooksCourierStatusSyncRouteImport.update({
    id: '/api/public/hooks/courier-status-sync',
    path: '/api/public/hooks/courier-status-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicFacebookPageOrdersWebhookRoute =
  ApiPublicFacebookPageOrdersWebhookRouteImport.update({
    id: '/api/public/facebook-page-orders/webhook',
    path: '/api/public/facebook-page-orders/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOrdersOrderIdInvoiceRoute = AppOrdersOrderIdInvoiceRouteImport.update({
  id: '/$orderId/invoice',
  path: '/$orderId/invoice',
  getParentRoute: () => AppOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auto-call': typeof AutoCallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/advance-payment-sources': typeof AppAdvancePaymentSourcesRoute
  '/categories': typeof AppCategoriesRoute
  '/chat-settings': typeof AppChatSettingsRoute
  '/complaints': typeof AppComplaintsRoute
  '/courier-settings': typeof AppCourierSettingsRoute
  '/couriers': typeof AppCouriersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/db-setup': typeof AppDbSetupRoute
  '/expenses': typeof AppExpensesRouteWithChildren
  '/facebook-orders': typeof AppFacebookOrdersRouteWithChildren
  '/incomplete-orders': typeof AppIncompleteOrdersRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/invoice-numbering-settings': typeof AppInvoiceNumberingSettingsRoute
  '/invoice-sticker-settings': typeof AppInvoiceStickerSettingsRoute
  '/marketing': typeof AppMarketingRouteWithChildren
  '/oms-endpoints': typeof AppOmsEndpointsRoute
  '/order-page-templates': typeof AppOrderPageTemplatesRoute
  '/order-sources': typeof AppOrderSourcesRoute
  '/orders': typeof AppOrdersRouteWithChildren
  '/preorders': typeof AppPreordersRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sms': typeof AppSmsRoute
  '/sms-settings': typeof AppSmsSettingsRoute
  '/staff-live': typeof AppStaffLiveRoute
  '/staff-reports': typeof AppStaffReportsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/telesales': typeof AppTelesalesRoute
  '/users': typeof AppUsersRoute
  '/web-orders': typeof AppWebOrdersRoute
  '/couriers/$courierId': typeof AppCouriersCourierIdRoute
  '/customers/blocked': typeof AppCustomersBlockedRoute
  '/expenses/accounts': typeof AppExpensesAccountsRoute
  '/expenses/history': typeof AppExpensesHistoryRoute
  '/expenses/pnl': typeof AppExpensesPnlRoute
  '/expenses/recurring': typeof AppExpensesRecurringRoute
  '/facebook-orders/logs': typeof AppFacebookOrdersLogsRoute
  '/facebook-orders/orders': typeof AppFacebookOrdersOrdersRoute
  '/facebook-orders/pages': typeof AppFacebookOrdersPagesRoute
  '/facebook-orders/settings': typeof AppFacebookOrdersSettingsRoute
  '/marketing/settings': typeof AppMarketingSettingsRoute
  '/marketing/sms': typeof AppMarketingSmsRoute
  '/marketing/templates': typeof AppMarketingTemplatesRoute
  '/marketing/whatsapp': typeof AppMarketingWhatsappRoute
  '/orders/bulk-invoice': typeof AppOrdersBulkInvoiceRoute
  '/orders/bulk-print': typeof AppOrdersBulkPrintRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/reports': typeof AppTasksReportsRoute
  '/api/public/oms-inbound': typeof ApiPublicOmsInboundRoute
  '/api/public/oms-products': typeof ApiPublicOmsProductsRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/facebook-orders/': typeof AppFacebookOrdersIndexRoute
  '/marketing/': typeof AppMarketingIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/api/public/facebook-page-orders/webhook': typeof ApiPublicFacebookPageOrdersWebhookRoute
  '/api/public/hooks/courier-status-sync': typeof ApiPublicHooksCourierStatusSyncRoute
  '/api/public/hooks/meta-ads-sync': typeof ApiPublicHooksMetaAdsSyncRoute
  '/api/public/hooks/woo-orders-sync': typeof ApiPublicHooksWooOrdersSyncRoute
  '/api/public/hooks/wp-incomplete-sync': typeof ApiPublicHooksWpIncompleteSyncRoute
  '/api/public/webhooks/woocommerce': typeof ApiPublicWebhooksWoocommerceRoute
  '/api/public/webhooks/wp-incomplete': typeof ApiPublicWebhooksWpIncompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auto-call': typeof AutoCallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/advance-payment-sources': typeof AppAdvancePaymentSourcesRoute
  '/categories': typeof AppCategoriesRoute
  '/chat-settings': typeof AppChatSettingsRoute
  '/complaints': typeof AppComplaintsRoute
  '/courier-settings': typeof AppCourierSettingsRoute
  '/couriers': typeof AppCouriersRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/db-setup': typeof AppDbSetupRoute
  '/incomplete-orders': typeof AppIncompleteOrdersRoute
  '/integrations': typeof AppIntegrationsRoute
  '/inventory': typeof AppInventoryRoute
  '/invoice-numbering-settings': typeof AppInvoiceNumberingSettingsRoute
  '/invoice-sticker-settings': typeof AppInvoiceStickerSettingsRoute
  '/oms-endpoints': typeof AppOmsEndpointsRoute
  '/order-page-templates': typeof AppOrderPageTemplatesRoute
  '/order-sources': typeof AppOrderSourcesRoute
  '/preorders': typeof AppPreordersRoute
  '/products': typeof AppProductsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sms': typeof AppSmsRoute
  '/sms-settings': typeof AppSmsSettingsRoute
  '/staff-live': typeof AppStaffLiveRoute
  '/staff-reports': typeof AppStaffReportsRoute
  '/tasks': typeof AppTasksRouteWithChildren
  '/telesales': typeof AppTelesalesRoute
  '/users': typeof AppUsersRoute
  '/web-orders': typeof AppWebOrdersRoute
  '/couriers/$courierId': typeof AppCouriersCourierIdRoute
  '/customers/blocked': typeof AppCustomersBlockedRoute
  '/expenses/accounts': typeof AppExpensesAccountsRoute
  '/expenses/history': typeof AppExpensesHistoryRoute
  '/expenses/pnl': typeof AppExpensesPnlRoute
  '/expenses/recurring': typeof AppExpensesRecurringRoute
  '/facebook-orders/logs': typeof AppFacebookOrdersLogsRoute
  '/facebook-orders/orders': typeof AppFacebookOrdersOrdersRoute
  '/facebook-orders/pages': typeof AppFacebookOrdersPagesRoute
  '/facebook-orders/settings': typeof AppFacebookOrdersSettingsRoute
  '/marketing/settings': typeof AppMarketingSettingsRoute
  '/marketing/sms': typeof AppMarketingSmsRoute
  '/marketing/templates': typeof AppMarketingTemplatesRoute
  '/marketing/whatsapp': typeof AppMarketingWhatsappRoute
  '/orders/bulk-invoice': typeof AppOrdersBulkInvoiceRoute
  '/orders/bulk-print': typeof AppOrdersBulkPrintRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/tasks/reports': typeof AppTasksReportsRoute
  '/api/public/oms-inbound': typeof ApiPublicOmsInboundRoute
  '/api/public/oms-products': typeof ApiPublicOmsProductsRoute
  '/customers': typeof AppCustomersIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/facebook-orders': typeof AppFacebookOrdersIndexRoute
  '/marketing': typeof AppMarketingIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/api/public/facebook-page-orders/webhook': typeof ApiPublicFacebookPageOrdersWebhookRoute
  '/api/public/hooks/courier-status-sync': typeof ApiPublicHooksCourierStatusSyncRoute
  '/api/public/hooks/meta-ads-sync': typeof ApiPublicHooksMetaAdsSyncRoute
  '/api/public/hooks/woo-orders-sync': typeof ApiPublicHooksWooOrdersSyncRoute
  '/api/public/hooks/wp-incomplete-sync': typeof ApiPublicHooksWpIncompleteSyncRoute
  '/api/public/webhooks/woocommerce': typeof ApiPublicWebhooksWoocommerceRoute
  '/api/public/webhooks/wp-incomplete': typeof ApiPublicWebhooksWpIncompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/auto-call': typeof AutoCallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/advance-payment-sources': typeof AppAdvancePaymentSourcesRoute
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/chat-settings': typeof AppChatSettingsRoute
  '/_app/complaints': typeof AppComplaintsRoute
  '/_app/courier-settings': typeof AppCourierSettingsRoute
  '/_app/couriers': typeof AppCouriersRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/db-setup': typeof AppDbSetupRoute
  '/_app/expenses': typeof AppExpensesRouteWithChildren
  '/_app/facebook-orders': typeof AppFacebookOrdersRouteWithChildren
  '/_app/incomplete-orders': typeof AppIncompleteOrdersRoute
  '/_app/integrations': typeof AppIntegrationsRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/invoice-numbering-settings': typeof AppInvoiceNumberingSettingsRoute
  '/_app/invoice-sticker-settings': typeof AppInvoiceStickerSettingsRoute
  '/_app/marketing': typeof AppMarketingRouteWithChildren
  '/_app/oms-endpoints': typeof AppOmsEndpointsRoute
  '/_app/order-page-templates': typeof AppOrderPageTemplatesRoute
  '/_app/order-sources': typeof AppOrderSourcesRoute
  '/_app/orders': typeof AppOrdersRouteWithChildren
  '/_app/preorders': typeof AppPreordersRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sms': typeof AppSmsRoute
  '/_app/sms-settings': typeof AppSmsSettingsRoute
  '/_app/staff-live': typeof AppStaffLiveRoute
  '/_app/staff-reports': typeof AppStaffReportsRoute
  '/_app/tasks': typeof AppTasksRouteWithChildren
  '/_app/telesales': typeof AppTelesalesRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/web-orders': typeof AppWebOrdersRoute
  '/_app/couriers/$courierId': typeof AppCouriersCourierIdRoute
  '/_app/customers/blocked': typeof AppCustomersBlockedRoute
  '/_app/expenses/accounts': typeof AppExpensesAccountsRoute
  '/_app/expenses/history': typeof AppExpensesHistoryRoute
  '/_app/expenses/pnl': typeof AppExpensesPnlRoute
  '/_app/expenses/recurring': typeof AppExpensesRecurringRoute
  '/_app/facebook-orders/logs': typeof AppFacebookOrdersLogsRoute
  '/_app/facebook-orders/orders': typeof AppFacebookOrdersOrdersRoute
  '/_app/facebook-orders/pages': typeof AppFacebookOrdersPagesRoute
  '/_app/facebook-orders/settings': typeof AppFacebookOrdersSettingsRoute
  '/_app/marketing/settings': typeof AppMarketingSettingsRoute
  '/_app/marketing/sms': typeof AppMarketingSmsRoute
  '/_app/marketing/templates': typeof AppMarketingTemplatesRoute
  '/_app/marketing/whatsapp': typeof AppMarketingWhatsappRoute
  '/_app/orders/bulk-invoice': typeof AppOrdersBulkInvoiceRoute
  '/_app/orders/bulk-print': typeof AppOrdersBulkPrintRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/tasks/$taskId': typeof AppTasksTaskIdRoute
  '/_app/tasks/reports': typeof AppTasksReportsRoute
  '/api/public/oms-inbound': typeof ApiPublicOmsInboundRoute
  '/api/public/oms-products': typeof ApiPublicOmsProductsRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/facebook-orders/': typeof AppFacebookOrdersIndexRoute
  '/_app/marketing/': typeof AppMarketingIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/orders/$orderId/invoice': typeof AppOrdersOrderIdInvoiceRoute
  '/api/public/facebook-page-orders/webhook': typeof ApiPublicFacebookPageOrdersWebhookRoute
  '/api/public/hooks/courier-status-sync': typeof ApiPublicHooksCourierStatusSyncRoute
  '/api/public/hooks/meta-ads-sync': typeof ApiPublicHooksMetaAdsSyncRoute
  '/api/public/hooks/woo-orders-sync': typeof ApiPublicHooksWooOrdersSyncRoute
  '/api/public/hooks/wp-incomplete-sync': typeof ApiPublicHooksWpIncompleteSyncRoute
  '/api/public/webhooks/woocommerce': typeof ApiPublicWebhooksWoocommerceRoute
  '/api/public/webhooks/wp-incomplete': typeof ApiPublicWebhooksWpIncompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auto-call'
    | '/reset-password'
    | '/advance-payment-sources'
    | '/categories'
    | '/chat-settings'
    | '/complaints'
    | '/courier-settings'
    | '/couriers'
    | '/dashboard'
    | '/db-setup'
    | '/expenses'
    | '/facebook-orders'
    | '/incomplete-orders'
    | '/integrations'
    | '/inventory'
    | '/invoice-numbering-settings'
    | '/invoice-sticker-settings'
    | '/marketing'
    | '/oms-endpoints'
    | '/order-page-templates'
    | '/order-sources'
    | '/orders'
    | '/preorders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/sms'
    | '/sms-settings'
    | '/staff-live'
    | '/staff-reports'
    | '/tasks'
    | '/telesales'
    | '/users'
    | '/web-orders'
    | '/couriers/$courierId'
    | '/customers/blocked'
    | '/expenses/accounts'
    | '/expenses/history'
    | '/expenses/pnl'
    | '/expenses/recurring'
    | '/facebook-orders/logs'
    | '/facebook-orders/orders'
    | '/facebook-orders/pages'
    | '/facebook-orders/settings'
    | '/marketing/settings'
    | '/marketing/sms'
    | '/marketing/templates'
    | '/marketing/whatsapp'
    | '/orders/bulk-invoice'
    | '/orders/bulk-print'
    | '/orders/new'
    | '/tasks/$taskId'
    | '/tasks/reports'
    | '/api/public/oms-inbound'
    | '/api/public/oms-products'
    | '/customers/'
    | '/expenses/'
    | '/facebook-orders/'
    | '/marketing/'
    | '/orders/'
    | '/orders/$orderId/invoice'
    | '/api/public/facebook-page-orders/webhook'
    | '/api/public/hooks/courier-status-sync'
    | '/api/public/hooks/meta-ads-sync'
    | '/api/public/hooks/woo-orders-sync'
    | '/api/public/hooks/wp-incomplete-sync'
    | '/api/public/webhooks/woocommerce'
    | '/api/public/webhooks/wp-incomplete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auto-call'
    | '/reset-password'
    | '/advance-payment-sources'
    | '/categories'
    | '/chat-settings'
    | '/complaints'
    | '/courier-settings'
    | '/couriers'
    | '/dashboard'
    | '/db-setup'
    | '/incomplete-orders'
    | '/integrations'
    | '/inventory'
    | '/invoice-numbering-settings'
    | '/invoice-sticker-settings'
    | '/oms-endpoints'
    | '/order-page-templates'
    | '/order-sources'
    | '/preorders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/sms'
    | '/sms-settings'
    | '/staff-live'
    | '/staff-reports'
    | '/tasks'
    | '/telesales'
    | '/users'
    | '/web-orders'
    | '/couriers/$courierId'
    | '/customers/blocked'
    | '/expenses/accounts'
    | '/expenses/history'
    | '/expenses/pnl'
    | '/expenses/recurring'
    | '/facebook-orders/logs'
    | '/facebook-orders/orders'
    | '/facebook-orders/pages'
    | '/facebook-orders/settings'
    | '/marketing/settings'
    | '/marketing/sms'
    | '/marketing/templates'
    | '/marketing/whatsapp'
    | '/orders/bulk-invoice'
    | '/orders/bulk-print'
    | '/orders/new'
    | '/tasks/$taskId'
    | '/tasks/reports'
    | '/api/public/oms-inbound'
    | '/api/public/oms-products'
    | '/customers'
    | '/expenses'
    | '/facebook-orders'
    | '/marketing'
    | '/orders'
    | '/orders/$orderId/invoice'
    | '/api/public/facebook-page-orders/webhook'
    | '/api/public/hooks/courier-status-sync'
    | '/api/public/hooks/meta-ads-sync'
    | '/api/public/hooks/woo-orders-sync'
    | '/api/public/hooks/wp-incomplete-sync'
    | '/api/public/webhooks/woocommerce'
    | '/api/public/webhooks/wp-incomplete'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/auto-call'
    | '/reset-password'
    | '/_app/advance-payment-sources'
    | '/_app/categories'
    | '/_app/chat-settings'
    | '/_app/complaints'
    | '/_app/courier-settings'
    | '/_app/couriers'
    | '/_app/dashboard'
    | '/_app/db-setup'
    | '/_app/expenses'
    | '/_app/facebook-orders'
    | '/_app/incomplete-orders'
    | '/_app/integrations'
    | '/_app/inventory'
    | '/_app/invoice-numbering-settings'
    | '/_app/invoice-sticker-settings'
    | '/_app/marketing'
    | '/_app/oms-endpoints'
    | '/_app/order-page-templates'
    | '/_app/order-sources'
    | '/_app/orders'
    | '/_app/preorders'
    | '/_app/products'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sms'
    | '/_app/sms-settings'
    | '/_app/staff-live'
    | '/_app/staff-reports'
    | '/_app/tasks'
    | '/_app/telesales'
    | '/_app/users'
    | '/_app/web-orders'
    | '/_app/couriers/$courierId'
    | '/_app/customers/blocked'
    | '/_app/expenses/accounts'
    | '/_app/expenses/history'
    | '/_app/expenses/pnl'
    | '/_app/expenses/recurring'
    | '/_app/facebook-orders/logs'
    | '/_app/facebook-orders/orders'
    | '/_app/facebook-orders/pages'
    | '/_app/facebook-orders/settings'
    | '/_app/marketing/settings'
    | '/_app/marketing/sms'
    | '/_app/marketing/templates'
    | '/_app/marketing/whatsapp'
    | '/_app/orders/bulk-invoice'
    | '/_app/orders/bulk-print'
    | '/_app/orders/new'
    | '/_app/tasks/$taskId'
    | '/_app/tasks/reports'
    | '/api/public/oms-inbound'
    | '/api/public/oms-products'
    | '/_app/customers/'
    | '/_app/expenses/'
    | '/_app/facebook-orders/'
    | '/_app/marketing/'
    | '/_app/orders/'
    | '/_app/orders/$orderId/invoice'
    | '/api/public/facebook-page-orders/webhook'
    | '/api/public/hooks/courier-status-sync'
    | '/api/public/hooks/meta-ads-sync'
    | '/api/public/hooks/woo-orders-sync'
    | '/api/public/hooks/wp-incomplete-sync'
    | '/api/public/webhooks/woocommerce'
    | '/api/public/webhooks/wp-incomplete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  AutoCallRoute: typeof AutoCallRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicOmsInboundRoute: typeof ApiPublicOmsInboundRoute
  ApiPublicOmsProductsRoute: typeof ApiPublicOmsProductsRoute
  ApiPublicFacebookPageOrdersWebhookRoute: typeof ApiPublicFacebookPageOrdersWebhookRoute
  ApiPublicHooksCourierStatusSyncRoute: typeof ApiPublicHooksCourierStatusSyncRoute
  ApiPublicHooksMetaAdsSyncRoute: typeof ApiPublicHooksMetaAdsSyncRoute
  ApiPublicHooksWooOrdersSyncRoute: typeof ApiPublicHooksWooOrdersSyncRoute
  ApiPublicHooksWpIncompleteSyncRoute: typeof ApiPublicHooksWpIncompleteSyncRoute
  ApiPublicWebhooksWoocommerceRoute: typeof ApiPublicWebhooksWoocommerceRoute
  ApiPublicWebhooksWpIncompleteRoute: typeof ApiPublicWebhooksWpIncompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auto-call': {
      id: '/auto-call'
      path: '/auto-call'
      fullPath: '/auto-call'
      preLoaderRoute: typeof AutoCallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/web-orders': {
      id: '/_app/web-orders'
      path: '/web-orders'
      fullPath: '/web-orders'
      preLoaderRoute: typeof AppWebOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/telesales': {
      id: '/_app/telesales'
      path: '/telesales'
      fullPath: '/telesales'
      preLoaderRoute: typeof AppTelesalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-reports': {
      id: '/_app/staff-reports'
      path: '/staff-reports'
      fullPath: '/staff-reports'
      preLoaderRoute: typeof AppStaffReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/staff-live': {
      id: '/_app/staff-live'
      path: '/staff-live'
      fullPath: '/staff-live'
      preLoaderRoute: typeof AppStaffLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sms-settings': {
      id: '/_app/sms-settings'
      path: '/sms-settings'
      fullPath: '/sms-settings'
      preLoaderRoute: typeof AppSmsSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sms': {
      id: '/_app/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof AppSmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preorders': {
      id: '/_app/preorders'
      path: '/preorders'
      fullPath: '/preorders'
      preLoaderRoute: typeof AppPreordersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order-sources': {
      id: '/_app/order-sources'
      path: '/order-sources'
      fullPath: '/order-sources'
      preLoaderRoute: typeof AppOrderSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/order-page-templates': {
      id: '/_app/order-page-templates'
      path: '/order-page-templates'
      fullPath: '/order-page-templates'
      preLoaderRoute: typeof AppOrderPageTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/oms-endpoints': {
      id: '/_app/oms-endpoints'
      path: '/oms-endpoints'
      fullPath: '/oms-endpoints'
      preLoaderRoute: typeof AppOmsEndpointsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing': {
      id: '/_app/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AppMarketingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoice-sticker-settings': {
      id: '/_app/invoice-sticker-settings'
      path: '/invoice-sticker-settings'
      fullPath: '/invoice-sticker-settings'
      preLoaderRoute: typeof AppInvoiceStickerSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoice-numbering-settings': {
      id: '/_app/invoice-numbering-settings'
      path: '/invoice-numbering-settings'
      fullPath: '/invoice-numbering-settings'
      preLoaderRoute: typeof AppInvoiceNumberingSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/integrations': {
      id: '/_app/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/incomplete-orders': {
      id: '/_app/incomplete-orders'
      path: '/incomplete-orders'
      fullPath: '/incomplete-orders'
      preLoaderRoute: typeof AppIncompleteOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/facebook-orders': {
      id: '/_app/facebook-orders'
      path: '/facebook-orders'
      fullPath: '/facebook-orders'
      preLoaderRoute: typeof AppFacebookOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/db-setup': {
      id: '/_app/db-setup'
      path: '/db-setup'
      fullPath: '/db-setup'
      preLoaderRoute: typeof AppDbSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/couriers': {
      id: '/_app/couriers'
      path: '/couriers'
      fullPath: '/couriers'
      preLoaderRoute: typeof AppCouriersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courier-settings': {
      id: '/_app/courier-settings'
      path: '/courier-settings'
      fullPath: '/courier-settings'
      preLoaderRoute: typeof AppCourierSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/complaints': {
      id: '/_app/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof AppComplaintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat-settings': {
      id: '/_app/chat-settings'
      path: '/chat-settings'
      fullPath: '/chat-settings'
      preLoaderRoute: typeof AppChatSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advance-payment-sources': {
      id: '/_app/advance-payment-sources'
      path: '/advance-payment-sources'
      fullPath: '/advance-payment-sources'
      preLoaderRoute: typeof AppAdvancePaymentSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/marketing/': {
      id: '/_app/marketing/'
      path: '/'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AppMarketingIndexRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/facebook-orders/': {
      id: '/_app/facebook-orders/'
      path: '/'
      fullPath: '/facebook-orders/'
      preLoaderRoute: typeof AppFacebookOrdersIndexRouteImport
      parentRoute: typeof AppFacebookOrdersRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/oms-products': {
      id: '/api/public/oms-products'
      path: '/api/public/oms-products'
      fullPath: '/api/public/oms-products'
      preLoaderRoute: typeof ApiPublicOmsProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oms-inbound': {
      id: '/api/public/oms-inbound'
      path: '/api/public/oms-inbound'
      fullPath: '/api/public/oms-inbound'
      preLoaderRoute: typeof ApiPublicOmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks/reports': {
      id: '/_app/tasks/reports'
      path: '/reports'
      fullPath: '/tasks/reports'
      preLoaderRoute: typeof AppTasksReportsRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/tasks/$taskId': {
      id: '/_app/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof AppTasksTaskIdRouteImport
      parentRoute: typeof AppTasksRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/orders/bulk-print': {
      id: '/_app/orders/bulk-print'
      path: '/bulk-print'
      fullPath: '/orders/bulk-print'
      preLoaderRoute: typeof AppOrdersBulkPrintRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/orders/bulk-invoice': {
      id: '/_app/orders/bulk-invoice'
      path: '/bulk-invoice'
      fullPath: '/orders/bulk-invoice'
      preLoaderRoute: typeof AppOrdersBulkInvoiceRouteImport
      parentRoute: typeof AppOrdersRoute
    }
    '/_app/marketing/whatsapp': {
      id: '/_app/marketing/whatsapp'
      path: '/whatsapp'
      fullPath: '/marketing/whatsapp'
      preLoaderRoute: typeof AppMarketingWhatsappRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/templates': {
      id: '/_app/marketing/templates'
      path: '/templates'
      fullPath: '/marketing/templates'
      preLoaderRoute: typeof AppMarketingTemplatesRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/sms': {
      id: '/_app/marketing/sms'
      path: '/sms'
      fullPath: '/marketing/sms'
      preLoaderRoute: typeof AppMarketingSmsRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/marketing/settings': {
      id: '/_app/marketing/settings'
      path: '/settings'
      fullPath: '/marketing/settings'
      preLoaderRoute: typeof AppMarketingSettingsRouteImport
      parentRoute: typeof AppMarketingRoute
    }
    '/_app/facebook-orders/settings': {
      id: '/_app/facebook-orders/settings'
      path: '/settings'
      fullPath: '/facebook-orders/settings'
      preLoaderRoute: typeof AppFacebookOrdersSettingsRouteImport
      parentRoute: typeof AppFacebookOrdersRoute
    }
    '/_app/facebook-orders/pages': {
      id: '/_app/facebook-orders/pages'
      path: '/pages'
      fullPath: '/facebook-orders/pages'
      preLoaderRoute: typeof AppFacebookOrdersPagesRouteImport
      parentRoute: typeof AppFacebookOrdersRoute
    }
    '/_app/facebook-orders/orders': {
      id: '/_app/facebook-orders/orders'
      path: '/orders'
      fullPath: '/facebook-orders/orders'
      preLoaderRoute: typeof AppFacebookOrdersOrdersRouteImport
      parentRoute: typeof AppFacebookOrdersRoute
    }
    '/_app/facebook-orders/logs': {
      id: '/_app/facebook-orders/logs'
      path: '/logs'
      fullPath: '/facebook-orders/logs'
      preLoaderRoute: typeof AppFacebookOrdersLogsRouteImport
      parentRoute: typeof AppFacebookOrdersRoute
    }
    '/_app/expenses/recurring': {
      id: '/_app/expenses/recurring'
      path: '/recurring'
      fullPath: '/expenses/recurring'
      preLoaderRoute: typeof AppExpensesRecurringRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/expenses/pnl': {
      id: '/_app/expenses/pnl'
      path: '/pnl'
      fullPath: '/expenses/pnl'
      preLoaderRoute: typeof AppExpensesPnlRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/expenses/history': {
      id: '/_app/expenses/history'
      path: '/history'
      fullPath: '/expenses/history'
      preLoaderRoute: typeof AppExpensesHistoryRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/expenses/accounts': {
      id: '/_app/expenses/accounts'
      path: '/accounts'
      fullPath: '/expenses/accounts'
      preLoaderRoute: typeof AppExpensesAccountsRouteImport
      parentRoute: typeof AppExpensesRoute
    }
    '/_app/customers/blocked': {
      id: '/_app/customers/blocked'
      path: '/customers/blocked'
      fullPath: '/customers/blocked'
      preLoaderRoute: typeof AppCustomersBlockedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/couriers/$courierId': {
      id: '/_app/couriers/$courierId'
      path: '/$courierId'
      fullPath: '/couriers/$courierId'
      preLoaderRoute: typeof AppCouriersCourierIdRouteImport
      parentRoute: typeof AppCouriersRoute
    }
    '/api/public/webhooks/wp-incomplete': {
      id: '/api/public/webhooks/wp-incomplete'
      path: '/api/public/webhooks/wp-incomplete'
      fullPath: '/api/public/webhooks/wp-incomplete'
      preLoaderRoute: typeof ApiPublicWebhooksWpIncompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/woocommerce': {
      id: '/api/public/webhooks/woocommerce'
      path: '/api/public/webhooks/woocommerce'
      fullPath: '/api/public/webhooks/woocommerce'
      preLoaderRoute: typeof ApiPublicWebhooksWoocommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/wp-incomplete-sync': {
      id: '/api/public/hooks/wp-incomplete-sync'
      path: '/api/public/hooks/wp-incomplete-sync'
      fullPath: '/api/public/hooks/wp-incomplete-sync'
      preLoaderRoute: typeof ApiPublicHooksWpIncompleteSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/woo-orders-sync': {
      id: '/api/public/hooks/woo-orders-sync'
      path: '/api/public/hooks/woo-orders-sync'
      fullPath: '/api/public/hooks/woo-orders-sync'
      preLoaderRoute: typeof ApiPublicHooksWooOrdersSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/meta-ads-sync': {
      id: '/api/public/hooks/meta-ads-sync'
      path: '/api/public/hooks/meta-ads-sync'
      fullPath: '/api/public/hooks/meta-ads-sync'
      preLoaderRoute: typeof ApiPublicHooksMetaAdsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/courier-status-sync': {
      id: '/api/public/hooks/courier-status-sync'
      path: '/api/public/hooks/courier-status-sync'
      fullPath: '/api/public/hooks/courier-status-sync'
      preLoaderRoute: typeof ApiPublicHooksCourierStatusSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/facebook-page-orders/webhook': {
      id: '/api/public/facebook-page-orders/webhook'
      path: '/api/public/facebook-page-orders/webhook'
      fullPath: '/api/public/facebook-page-orders/webhook'
      preLoaderRoute: typeof ApiPublicFacebookPageOrdersWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/orders/$orderId/invoice': {
      id: '/_app/orders/$orderId/invoice'
      path: '/$orderId/invoice'
      fullPath: '/orders/$orderId/invoice'
      preLoaderRoute: typeof AppOrdersOrderIdInvoiceRouteImport
      parentRoute: typeof AppOrdersRoute
    }
  }
}

interface AppCouriersRouteChildren {
  AppCouriersCourierIdRoute: typeof AppCouriersCourierIdRoute
}

const AppCouriersRouteChildren: AppCouriersRouteChildren = {
  AppCouriersCourierIdRoute: AppCouriersCourierIdRoute,
}

const AppCouriersRouteWithChildren = AppCouriersRoute._addFileChildren(
  AppCouriersRouteChildren,
)

interface AppExpensesRouteChildren {
  AppExpensesAccountsRoute: typeof AppExpensesAccountsRoute
  AppExpensesHistoryRoute: typeof AppExpensesHistoryRoute
  AppExpensesPnlRoute: typeof AppExpensesPnlRoute
  AppExpensesRecurringRoute: typeof AppExpensesRecurringRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
}

const AppExpensesRouteChildren: AppExpensesRouteChildren = {
  AppExpensesAccountsRoute: AppExpensesAccountsRoute,
  AppExpensesHistoryRoute: AppExpensesHistoryRoute,
  AppExpensesPnlRoute: AppExpensesPnlRoute,
  AppExpensesRecurringRoute: AppExpensesRecurringRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
}

const AppExpensesRouteWithChildren = AppExpensesRoute._addFileChildren(
  AppExpensesRouteChildren,
)

interface AppFacebookOrdersRouteChildren {
  AppFacebookOrdersLogsRoute: typeof AppFacebookOrdersLogsRoute
  AppFacebookOrdersOrdersRoute: typeof AppFacebookOrdersOrdersRoute
  AppFacebookOrdersPagesRoute: typeof AppFacebookOrdersPagesRoute
  AppFacebookOrdersSettingsRoute: typeof AppFacebookOrdersSettingsRoute
  AppFacebookOrdersIndexRoute: typeof AppFacebookOrdersIndexRoute
}

const AppFacebookOrdersRouteChildren: AppFacebookOrdersRouteChildren = {
  AppFacebookOrdersLogsRoute: AppFacebookOrdersLogsRoute,
  AppFacebookOrdersOrdersRoute: AppFacebookOrdersOrdersRoute,
  AppFacebookOrdersPagesRoute: AppFacebookOrdersPagesRoute,
  AppFacebookOrdersSettingsRoute: AppFacebookOrdersSettingsRoute,
  AppFacebookOrdersIndexRoute: AppFacebookOrdersIndexRoute,
}

const AppFacebookOrdersRouteWithChildren =
  AppFacebookOrdersRoute._addFileChildren(AppFacebookOrdersRouteChildren)

interface AppMarketingRouteChildren {
  AppMarketingSettingsRoute: typeof AppMarketingSettingsRoute
  AppMarketingSmsRoute: typeof AppMarketingSmsRoute
  AppMarketingTemplatesRoute: typeof AppMarketingTemplatesRoute
  AppMarketingWhatsappRoute: typeof AppMarketingWhatsappRoute
  AppMarketingIndexRoute: typeof AppMarketingIndexRoute
}

const AppMarketingRouteChildren: AppMarketingRouteChildren = {
  AppMarketingSettingsRoute: AppMarketingSettingsRoute,
  AppMarketingSmsRoute: AppMarketingSmsRoute,
  AppMarketingTemplatesRoute: AppMarketingTemplatesRoute,
  AppMarketingWhatsappRoute: AppMarketingWhatsappRoute,
  AppMarketingIndexRoute: AppMarketingIndexRoute,
}

const AppMarketingRouteWithChildren = AppMarketingRoute._addFileChildren(
  AppMarketingRouteChildren,
)

interface AppOrdersRouteChildren {
  AppOrdersBulkInvoiceRoute: typeof AppOrdersBulkInvoiceRoute
  AppOrdersBulkPrintRoute: typeof AppOrdersBulkPrintRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppOrdersOrderIdInvoiceRoute: typeof AppOrdersOrderIdInvoiceRoute
}

const AppOrdersRouteChildren: AppOrdersRouteChildren = {
  AppOrdersBulkInvoiceRoute: AppOrdersBulkInvoiceRoute,
  AppOrdersBulkPrintRoute: AppOrdersBulkPrintRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppOrdersOrderIdInvoiceRoute: AppOrdersOrderIdInvoiceRoute,
}

const AppOrdersRouteWithChildren = AppOrdersRoute._addFileChildren(
  AppOrdersRouteChildren,
)

interface AppTasksRouteChildren {
  AppTasksTaskIdRoute: typeof AppTasksTaskIdRoute
  AppTasksReportsRoute: typeof AppTasksReportsRoute
}

const AppTasksRouteChildren: AppTasksRouteChildren = {
  AppTasksTaskIdRoute: AppTasksTaskIdRoute,
  AppTasksReportsRoute: AppTasksReportsRoute,
}

const AppTasksRouteWithChildren = AppTasksRoute._addFileChildren(
  AppTasksRouteChildren,
)

interface AppRouteChildren {
  AppAdvancePaymentSourcesRoute: typeof AppAdvancePaymentSourcesRoute
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppChatSettingsRoute: typeof AppChatSettingsRoute
  AppComplaintsRoute: typeof AppComplaintsRoute
  AppCourierSettingsRoute: typeof AppCourierSettingsRoute
  AppCouriersRoute: typeof AppCouriersRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDbSetupRoute: typeof AppDbSetupRoute
  AppExpensesRoute: typeof AppExpensesRouteWithChildren
  AppFacebookOrdersRoute: typeof AppFacebookOrdersRouteWithChildren
  AppIncompleteOrdersRoute: typeof AppIncompleteOrdersRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppInvoiceNumberingSettingsRoute: typeof AppInvoiceNumberingSettingsRoute
  AppInvoiceStickerSettingsRoute: typeof AppInvoiceStickerSettingsRoute
  AppMarketingRoute: typeof AppMarketingRouteWithChildren
  AppOmsEndpointsRoute: typeof AppOmsEndpointsRoute
  AppOrderPageTemplatesRoute: typeof AppOrderPageTemplatesRoute
  AppOrderSourcesRoute: typeof AppOrderSourcesRoute
  AppOrdersRoute: typeof AppOrdersRouteWithChildren
  AppPreordersRoute: typeof AppPreordersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSmsRoute: typeof AppSmsRoute
  AppSmsSettingsRoute: typeof AppSmsSettingsRoute
  AppStaffLiveRoute: typeof AppStaffLiveRoute
  AppStaffReportsRoute: typeof AppStaffReportsRoute
  AppTasksRoute: typeof AppTasksRouteWithChildren
  AppTelesalesRoute: typeof AppTelesalesRoute
  AppUsersRoute: typeof AppUsersRoute
  AppWebOrdersRoute: typeof AppWebOrdersRoute
  AppCustomersBlockedRoute: typeof AppCustomersBlockedRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvancePaymentSourcesRoute: AppAdvancePaymentSourcesRoute,
  AppCategoriesRoute: AppCategoriesRoute,
  AppChatSettingsRoute: AppChatSettingsRoute,
  AppComplaintsRoute: AppComplaintsRoute,
  AppCourierSettingsRoute: AppCourierSettingsRoute,
  AppCouriersRoute: AppCouriersRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDbSetupRoute: AppDbSetupRoute,
  AppExpensesRoute: AppExpensesRouteWithChildren,
  AppFacebookOrdersRoute: AppFacebookOrdersRouteWithChildren,
  AppIncompleteOrdersRoute: AppIncompleteOrdersRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppInvoiceNumberingSettingsRoute: AppInvoiceNumberingSettingsRoute,
  AppInvoiceStickerSettingsRoute: AppInvoiceStickerSettingsRoute,
  AppMarketingRoute: AppMarketingRouteWithChildren,
  AppOmsEndpointsRoute: AppOmsEndpointsRoute,
  AppOrderPageTemplatesRoute: AppOrderPageTemplatesRoute,
  AppOrderSourcesRoute: AppOrderSourcesRoute,
  AppOrdersRoute: AppOrdersRouteWithChildren,
  AppPreordersRoute: AppPreordersRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSmsRoute: AppSmsRoute,
  AppSmsSettingsRoute: AppSmsSettingsRoute,
  AppStaffLiveRoute: AppStaffLiveRoute,
  AppStaffReportsRoute: AppStaffReportsRoute,
  AppTasksRoute: AppTasksRouteWithChildren,
  AppTelesalesRoute: AppTelesalesRoute,
  AppUsersRoute: AppUsersRoute,
  AppWebOrdersRoute: AppWebOrdersRoute,
  AppCustomersBlockedRoute: AppCustomersBlockedRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  AutoCallRoute: AutoCallRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicOmsInboundRoute: ApiPublicOmsInboundRoute,
  ApiPublicOmsProductsRoute: ApiPublicOmsProductsRoute,
  ApiPublicFacebookPageOrdersWebhookRoute:
    ApiPublicFacebookPageOrdersWebhookRoute,
  ApiPublicHooksCourierStatusSyncRoute: ApiPublicHooksCourierStatusSyncRoute,
  ApiPublicHooksMetaAdsSyncRoute: ApiPublicHooksMetaAdsSyncRoute,
  ApiPublicHooksWooOrdersSyncRoute: ApiPublicHooksWooOrdersSyncRoute,
  ApiPublicHooksWpIncompleteSyncRoute: ApiPublicHooksWpIncompleteSyncRoute,
  ApiPublicWebhooksWoocommerceRoute: ApiPublicWebhooksWoocommerceRoute,
  ApiPublicWebhooksWpIncompleteRoute: ApiPublicWebhooksWpIncompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
